# Generated by Django 5.1.7 on 2025-04-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_offer_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
